{"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onunprovisionresponse:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:14OpenpathMobile0aB18AccessCoreDelegateP08openpathbcD0_21onUnprovisionResponseyAA0abcD0C_SDySSypGtF","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openpathMobileAccessCore","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onUnprovisionResponse"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}],"title":"openpathMobileAccessCore(_:onUnprovisionResponse:)","required":true,"modules":[{"name":"OpenpathMobile"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openpathMobileAccessCore","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"openpathMobileAccessCore","kind":"internalParam"},{"kind":"text","text":": "},{"text":"OpenpathMobileAccessCore","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","kind":"typeIdentifier","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"text":"onUnprovisionResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The unprovision may be triggered by a call to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unprovision(userOpal:)"},{"type":"text","text":" in the SDK, but also if the SDK detects that the active user is not allowed to be provisioned, for example if the same user using the same credential provisioned the SDK on another device."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"code":"reasonCode","type":"codeVoice"},{"text":" and the ","type":"text"},{"code":"reasonDescription","type":"codeVoice"},{"type":"text","text":" objects returned in the message payload clarify the reason for this unprovision."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"In cases where the request to unprovision was to unprovision all users on the device ","type":"text"},{"code":"userOpal","type":"codeVoice"},{"type":"text","text":" is"},{"type":"codeVoice","code":"nil"}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Success message:","type":"text"}],"type":"emphasis"}]},{"type":"codeListing","code":["[","  \"data\": [","    \"userOpal\": String?,","    \"reasonCode\": Int,","    \"reasonDescription\": String","  ]","]"],"syntax":null}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Invoked when a user is unprovisioned."}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onUnprovisionResponse:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]]},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onUnprovisionResponse:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onUnprovisionResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"title":"openpathMobileAccessCore(_:onUnprovisionResponse:)","kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onunprovisionresponse:)","role":"symbol","abstract":[{"type":"text","text":"Invoked when a user is unprovisioned."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onUnprovisionResponse:)","required":true},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","type":"reference","isActive":true}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate","type":"topic","title":"OpenpathMobileAccessCoreDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"OpenpathMobileAccessCoreDelegate","kind":"identifier"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/unprovision(userOpal:)":{"abstract":[{"text":"Clears the Openpath user data for the requested user.","type":"text"}],"title":"unprovision(userOpal:)","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/unprovision(userOpal:)","type":"topic","kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/unprovision(useropal:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unprovision","kind":"identifier"},{"kind":"text","text":"("},{"text":"userOpal","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","abstract":[{"text":"The entry point for all functionality in the OpenpathMobile SDK.","type":"text"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","kind":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","op":"replace","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}