{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onInitializeUserRequest"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"modules":[{"name":"OpenpathMobile"}],"externalID":"s:14OpenpathMobile0aB18AccessCoreDelegateP08openpathbcD0_23onInitializeUserRequestyAA0abcD0C_SDySSypGtF","title":"openpathMobileAccessCore(_:onInitializeUserRequest:)","required":true,"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"openpathMobileAccessCore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onInitializeUserRequest"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:oninitializeuserrequest:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]]},"defaultImplementationsSections":[{"anchor":"OpenpathMobileAccessCoreDelegate-Implementations","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onInitializeUserRequest:)-3qs1e"],"title":"OpenpathMobileAccessCoreDelegate Implementations"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onInitializeUserRequest:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onInitializeUserRequest:)":{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onInitializeUserRequest:)","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:oninitializeuserrequest:)","title":"openpathMobileAccessCore(_:onInitializeUserRequest:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onInitializeUserRequest"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"kind":"symbol","type":"topic","defaultImplementations":1,"required":true,"role":"symbol","abstract":[]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"title":"OpenpathMobile","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onInitializeUserRequest:)-3qs1e":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:oninitializeuserrequest:)-3qs1e","title":"openpathMobileAccessCore(_:onInitializeUserRequest:)","type":"topic","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onInitializeUserRequest:)-3qs1e","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openpathMobileAccessCore","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onInitializeUserRequest","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"title":"OpenpathMobileAccessCoreDelegate","abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","type":"reference","isActive":true}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"type":"topic"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"title":"OpenpathMobileAccessCore","navigatorTitle":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","role":"symbol","abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle","value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}]}]}]}