{"defaultImplementationsSections":[{"title":"OpenpathMobileAccessCoreDelegate Implementations","anchor":"OpenpathMobileAccessCoreDelegate-Implementations","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-79o91"]}],"metadata":{"symbolKind":"method","externalID":"s:14OpenpathMobile0aB18AccessCoreDelegateP08openpathbcD0_32onRevertByConnectionTypeResponseyAA0abcD0C_SDySSypGtF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onRevertByConnectionTypeResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"required":true,"roleHeading":"Instance Method","title":"openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)","modules":[{"name":"OpenpathMobile"}],"role":"symbol"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"openpathMobileAccessCore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"},{"text":", ","kind":"text"},{"text":"onRevertByConnectionTypeResponse","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-4dtmz"},"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onrevertbyconnectiontyperesponse:)-4dtmz"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","abstract":[{"text":"The entry point for all functionality in the OpenpathMobile SDK.","type":"text"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","kind":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","type":"reference","isActive":true}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate","type":"topic","title":"OpenpathMobileAccessCoreDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"OpenpathMobileAccessCoreDelegate","kind":"identifier"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-4dtmz":{"kind":"symbol","title":"openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openpathMobileAccessCore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"typeIdentifier","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onRevertByConnectionTypeResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"defaultImplementations":1,"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-4dtmz","required":true,"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onrevertbyconnectiontyperesponse:)-4dtmz","type":"topic"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-79o91":{"title":"openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)","type":"topic","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onRevertByConnectionTypeResponse:)-79o91","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openpathMobileAccessCore","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"text":"onRevertByConnectionTypeResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onrevertbyconnectiontyperesponse:)-79o91"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","op":"replace","value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"op":"replace"}]}]}