{"metadata":{"symbolKind":"method","required":true,"title":"openpathMobileAccessCore(_:onBluetoothStatusChanged:)","modules":[{"name":"OpenpathMobile"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onBluetoothStatusChanged"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"externalID":"s:14OpenpathMobile0aB18AccessCoreDelegateP08openpathbcD0_24onBluetoothStatusChangedyAA0abcD0C_SDySSypGtF"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onBluetoothStatusChanged:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Invoked when bluetooth status has changed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"openpathMobileAccessCore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","kind":"typeIdentifier","text":"OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onBluetoothStatusChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"emphasis","inlineContent":[{"type":"text","text":"Success message:"}]}],"type":"paragraph"},{"syntax":null,"type":"codeListing","code":["[","  \"data\": [","    \"isBluetoothOn\": Bool,","    \"bluetoothPermissionSetting\": String","    \"isBluetoothRestarting\": Bool","  ]","]"]},{"inlineContent":[{"inlineContent":[{"type":"text","text":"bluetoothPermissionSetting"}],"type":"strong"},{"text":" options are:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"ios_allowedAlways"}],"type":"emphasis"}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"ios_restricted"}],"type":"emphasis"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"ios_notDetermined"}],"type":"emphasis"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"ios_denied","type":"text"}],"type":"emphasis"},{"text":".","type":"text"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onbluetoothstatuschanged:)"]}],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"title":"OpenpathMobileAccessCoreDelegate","abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","type":"reference","isActive":true}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"type":"topic"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"title":"OpenpathMobile","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"title":"OpenpathMobileAccessCore","navigatorTitle":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","role":"symbol","abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onBluetoothStatusChanged:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onBluetoothStatusChanged"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"kind":"symbol","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onbluetoothstatuschanged:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Invoked when bluetooth status has changed."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onBluetoothStatusChanged:)","title":"openpathMobileAccessCore(_:onBluetoothStatusChanged:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]}]}]}