{"sections":[],"defaultImplementationsSections":[{"anchor":"OpenpathMobileAccessCoreDelegate-Implementations","title":"OpenpathMobileAccessCoreDelegate Implementations","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onOverrideResponse:)-7j38j"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","externalID":"s:14OpenpathMobile0aB18AccessCoreDelegateP08openpathbcD0_18onOverrideResponseyAA0abcD0C_SDySSypGtF","title":"openpathMobileAccessCore(_:onOverrideResponse:)","roleHeading":"Instance Method","modules":[{"name":"OpenpathMobile"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onOverrideResponse"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"required":true},"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onOverrideResponse:)-77mi0","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"openpathMobileAccessCore","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"openpathMobileAccessCore"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onOverrideResponse","kind":"externalParam"},{"kind":"text","text":" "},{"text":"message","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onoverrideresponse:)-77mi0"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]]},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","abstract":[{"text":"The entry point for all functionality in the OpenpathMobile SDK.","type":"text"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","kind":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","type":"reference","isActive":true}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate","type":"topic","title":"OpenpathMobileAccessCoreDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"OpenpathMobileAccessCoreDelegate","kind":"identifier"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onOverrideResponse:)-7j38j":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openpathMobileAccessCore"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"OpenpathMobileAccessCore","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore"},{"kind":"text","text":", "},{"text":"onOverrideResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onoverrideresponse:)-7j38j","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onOverrideResponse:)-7j38j","title":"openpathMobileAccessCore(_:onOverrideResponse:)"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate/openpathMobileAccessCore(_:onOverrideResponse:)-77mi0":{"type":"topic","role":"symbol","title":"openpathMobileAccessCore(_:onOverrideResponse:)","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate\/openpathMobileAccessCore(_:onOverrideResponse:)-77mi0","url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate\/openpathmobileaccesscore(_:onoverrideresponse:)-77mi0","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openpathMobileAccessCore","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore","text":"OpenpathMobileAccessCore"},{"text":", ","kind":"text"},{"text":"onOverrideResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"defaultImplementations":1}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"OpenpathMobileAccessCore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title"},{"value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle","value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}]}]}]}