{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"OpenpathMobile"}],"externalID":"c:@M@OpenpathMobile@objc(cs)OpenpathMobileAccessCore(im)URLSession:didBecomeInvalidWithError:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didBecomeInvalidWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"symbolKind":"method","title":"urlSession(_:didBecomeInvalidWithError:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"URLSession:didBecomeInvalidWithError:"}]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"URLSessionDelegate.urlSession(_:didBecomeInvalidWithError:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"text":", ","kind":"text"},{"text":"didBecomeInvalidWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsession(_:didbecomeinvalidwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsession(_:didbecomeinvalidwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didBecomeInvalidWithError:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","abstract":[{"text":"The entry point for all functionality in the OpenpathMobile SDK.","type":"text"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","kind":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore/urlSession(_:didBecomeInvalidWithError:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore\/urlSession(_:didBecomeInvalidWithError:)","url":"\/documentation\/openpathmobile\/openpathmobileaccesscore\/urlsession(_:didbecomeinvalidwitherror:)","title":"urlSession(_:didBecomeInvalidWithError:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didBecomeInvalidWithError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"URLSession:didBecomeInvalidWithError:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"URLSession:didBecomeInvalidWithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"URLSession:didBecomeInvalidWithError:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"URLSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *) "},{"text":"_","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didBecomeInvalidWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},{"op":"replace","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didBecomeInvalidWithError:)\/title","op":"replace","value":"URLSession:didBecomeInvalidWithError:"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore~1urlSession(_:didBecomeInvalidWithError:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didBecomeInvalidWithError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}