{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"variants":[{"paths":["\/documentation\/openpathmobile\/joseswiftversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile\/joseswiftversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"JOSESwiftVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Project version string for JOSESwift.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/JOSESwiftVersionString"},"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JOSESwiftVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"JOSESwiftVersionString","kind":"identifier"}],"title":"JOSESwiftVersionString","roleHeading":"Global Variable","modules":[{"name":"OpenpathMobile"}],"symbolKind":"var","externalID":"c:@JOSESwiftVersionString"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/JOSESwiftVersionString":{"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/JOSESwiftVersionString","kind":"symbol","role":"symbol","url":"\/documentation\/openpathmobile\/joseswiftversionstring","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JOSESwiftVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"JOSESwiftVersionString","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version string for JOSESwift."}],"title":"JOSESwiftVersionString"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"title":"OpenpathMobile","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"JOSESwiftVersionString","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JOSESwiftVersionString","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:c","kind":"typeIdentifier","text":"unsigned char"},{"kind":"text","text":" "},{"kind":"identifier","text":"JOSESwiftVersionString"},{"kind":"text","text":"[];"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1JOSESwiftVersionString\/title","value":"JOSESwiftVersionString","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1JOSESwiftVersionString\/fragments","value":[{"text":"JOSESwiftVersionString","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}