{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/JOSESwiftVersionNumber"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JOSESwiftVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openpathmobile\/joseswiftversionnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile\/joseswiftversionnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Project version number for JOSESwift."}],"metadata":{"modules":[{"name":"OpenpathMobile"}],"symbolKind":"var","role":"symbol","externalID":"c:@JOSESwiftVersionNumber","roleHeading":"Global Variable","title":"JOSESwiftVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"JOSESwiftVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"JOSESwiftVersionNumber"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"sections":[],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"title":"OpenpathMobile","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/JOSESwiftVersionNumber":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/JOSESwiftVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JOSESwiftVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"text":"JOSESwiftVersionNumber","kind":"identifier"}],"url":"\/documentation\/openpathmobile\/joseswiftversionnumber","kind":"symbol","abstract":[{"text":"Project version number for JOSESwift.","type":"text"}],"title":"JOSESwiftVersionNumber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"JOSESwiftVersionNumber","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"JOSESwiftVersionNumber","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"JOSESwiftVersionNumber","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1JOSESwiftVersionNumber\/title","value":"JOSESwiftVersionNumber","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1JOSESwiftVersionNumber\/fragments","value":[{"text":"JOSESwiftVersionNumber","kind":"identifier"}],"op":"replace"}]}]}