{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionString"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"}],"role":"symbol","roleHeading":"Global Variable","externalID":"c:@ObjcExceptionBridgingVersionString","modules":[{"name":"OpenpathMobile"}],"title":"ObjcExceptionBridgingVersionString","symbolKind":"var","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObjcExceptionBridgingVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}]},"variants":[{"paths":["\/documentation\/openpathmobile\/objcexceptionbridgingversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openpathmobile\/objcexceptionbridgingversionstring"]}],"abstract":[{"type":"text","text":"Project version string for ObjcExceptionBridging."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"},{"text":": <<error type>>","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/ObjcExceptionBridgingVersionString":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"},{"kind":"text","text":": <<error type>>"}],"navigatorTitle":[{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Project version string for ObjcExceptionBridging."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionString","title":"ObjcExceptionBridgingVersionString","url":"\/documentation\/openpathmobile\/objcexceptionbridgingversionstring","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ObjcExceptionBridgingVersionString","op":"replace","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"text":" ","kind":"text"},{"text":"ObjcExceptionBridgingVersionString","kind":"identifier"},{"text":"[];","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1ObjcExceptionBridgingVersionString\/title","op":"replace","value":"ObjcExceptionBridgingVersionString"},{"value":[{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"}],"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1ObjcExceptionBridgingVersionString\/fragments","op":"replace"}]}]}