{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Article","modules":[{"name":"OpenpathMobile"}],"title":"iOS SDK Release v0.4.4","role":"article"},"primaryContentSections":[{"content":[{"anchor":"Release-Notes","level":2,"type":"heading","text":"Release Notes"},{"anchor":"Apple-Required-Reason-APIs","type":"heading","level":3,"text":"Apple Required Reason APIs"},{"inlineContent":[{"type":"text","text":"This update removes all usage of Apple’s Required Reason APIs in OpenpathMobileAccessCore code, and upgrades the SDK’s"},{"type":"text","text":" "},{"text":"dependencies to versions which either remove usage of those APIs or provide privacy manifest files.","type":"text"}],"type":"paragraph"},{"anchor":"Migration-Guide-from-043-to-044","text":"Migration Guide from 0.4.3 to 0.4.4","level":3,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Replace the existing v0.4.3 directory with the contents of this ZIP file."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"If you had a Cocoapods patch to work around the bug in the AWSIoT library version 2.31.1, that is no longer needed, as","type":"text"},{"text":" ","type":"text"},{"text":"that dependency has been updated to a newer version.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to other migration guides if you are migrating from an earlier SDK version."}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openpathmobile\/release-0.4.4"]},{"paths":["\/documentation\/openpathmobile\/release-0.4.4"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.4","interfaceLanguage":"swift"},"kind":"article","references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}