{"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.0","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"OpenpathMobile"}],"role":"article","title":"Release v0.1.0","roleHeading":"Article"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Release-Notes","text":"Release Notes"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Feature: added support for provisioning multiple user accounts and switching between them"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Feature: added support for the “geofence” location-based unlock method","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Feature: added “getSdkVersion” method","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Improvement: included error descriptions in unlock responses"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Improvement: improved error descriptions when unlock fails"}]}]},{"content":[{"inlineContent":[{"text":"Improvement: wave\/touch reliability improved upon app restart or device reboot","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Bug fix: only remove keychain and storage items (UserDefaults) created within SDK instead of everything created within app","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Migration-Guide","level":2,"type":"heading","text":"Migration Guide"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","isActive":true},{"text":" was updated to optimize the process of user initialization and to provide further support for applications with multiple user’s accounts.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The following function is ","type":"text"},{"inlineContent":[{"type":"text","text":"deprecated"}],"type":"strong"},{"text":":","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"func start(completion: @escaping (_ message: [String: Any]) -> Void)"}]},{"type":"paragraph","inlineContent":[{"text":"The following functions are introduced:","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"func switchUser(userOpal:String, completion: @escaping (_ message: [String: Any]) -> Void)"}]},{"inlineContent":[{"type":"codeVoice","code":"func syncUser(completion: @escaping (_ message: [String: Any]) -> Void)"}],"type":"paragraph"},{"anchor":"Provision-flow","level":3,"type":"heading","text":"Provision flow"},{"type":"paragraph","inlineContent":[{"text":"If you want to provision a new user, the code should be updated from calling ","type":"text"},{"code":"provision","type":"codeVoice"},{"type":"text","text":" and then "},{"code":"start","type":"codeVoice"},{"type":"text","text":" to the following 3-step process."}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"call "},{"code":"provision","type":"codeVoice"},{"text":" to provision a user","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call "},{"code":"switchUser","type":"codeVoice"},{"text":" to activate the user","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call "},{"type":"codeVoice","code":"syncUser"},{"text":" to receive all updated information for that user","type":"text"}]}]}]},{"text":"Switch User flow","anchor":"Switch-User-flow","level":3,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you simply want to switch the current user, you will use the following 2-step process."}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"call "},{"code":"switchUser","type":"codeVoice"},{"text":" to activate the user","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call "},{"code":"syncUser","type":"codeVoice"},{"text":" to receive all updated information for that user","type":"text"}]}]}],"type":"orderedList"},{"anchor":"Initializitation-flow","type":"heading","text":"Initializitation flow","level":3},{"inlineContent":[{"type":"text","text":"When the app first opens but is already provisioned, the code should be updated from just calling "},{"code":"start","type":"codeVoice"},{"type":"text","text":" to the following process."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call "},{"type":"codeVoice","code":"syncUser"},{"text":" to receive all updated information for that user","type":"text"}]}]}],"type":"orderedList"},{"type":"paragraph","inlineContent":[{"text":"The following changes were made to the sample app in order to implement proposed changes.","type":"text"}]},{"type":"thematicBreak"},{"anchor":"CocoaPods-updates","text":"CocoaPods updates","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"Update your Podfile to have the following dependencies:","type":"text"}]},{"type":"codeListing","code":["pod 'AWSCore', '=2.9.8'","pod 'AWSLogs', '=2.9.8'","pod 'XCGLogger', '= 7.0.0'","pod 'ReachabilitySwift', '= 5.0.0'","pod 'JWTDecode', '= 2.1'","pod 'MQTTClient', '= 0.15.2'","pod 'MQTTClient\/Websocket', '= 0.15.2'","pod 'SwiftSocket', '= 2.0.2'","pod 'BCryptSwift', '= 1.1'","pod 'OpenSSL-Universal\/Framework', '= 1.0.2.20'","pod 'CryptoSwift', '= 1.0'"],"syntax":null}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile"]]},"kind":"article","variants":[{"paths":["\/documentation\/openpathmobile\/release-0.1.0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openpathmobile\/release-0.1.0"]}],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","abstract":[{"text":"The entry point for all functionality in the OpenpathMobile SDK.","type":"text"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore","kind":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","url":"\/documentation\/openpathmobile","identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","type":"topic","kind":"symbol","abstract":[{"text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices.","type":"text"}],"title":"OpenpathMobile"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"OpenpathMobileAccessCore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"text":"OpenpathMobileAccessCore","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/navigatorTitle","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]}]}]}