//
// DescribeAccessToken200ResponseDataIdentityNamespace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataIdentityNamespace: Codable, JSONEncodable, Hashable {
    public var id: Double?
    public var nickname: String?

    public init(id: Double? = nil, nickname: String? = nil) {
        self.id = id
        self.nickname = nickname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case nickname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(nickname, forKey: .nickname)
    }
}
