//
// DescribeAccessToken200ResponseDataTokenScopeListInnerOrg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataTokenScopeListInnerOrg: Codable, JSONEncodable, Hashable {
    public var id: Int?
    public var name: String?
    public var opal: String?
    public var packagePlans: [DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInner]?
    public var parentOrg: ListCredentialConfigs200ResponseDataInnerOrg?

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case opal
        case packagePlans
        case parentOrg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(opal, forKey: .opal)
        try container.encodeIfPresent(packagePlans, forKey: .packagePlans)
        try container.encodeIfPresent(parentOrg, forKey: .parentOrg)
    }
}
