//
// DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInner: Codable, JSONEncodable,
    Hashable {
    public var id: Double?
    public var package: DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackage?
    public var isSelected: Bool?

    public init(
        id: Double? = nil,
        package: DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackage? = nil,
        isSelected: Bool? = nil
    ) {
        self.id = id
        self.package = package
        self.isSelected = isSelected
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case package
        case isSelected
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(package, forKey: .package)
        try container.encodeIfPresent(isSelected, forKey: .isSelected)
    }
}
