//
// DescribeAccessToken200ResponseDataIdentity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataIdentity: Codable, JSONEncodable, Hashable {
    public var id: Int
    public var namespace: DescribeAccessToken200ResponseDataIdentityNamespace?

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case namespace
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(namespace, forKey: .namespace)
    }
}
