//
// DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackage: Codable, JSONEncodable,
    Hashable {
    public var id: Double?
    public var name: String?
    public var packageFeatures: [
        DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackagePackageFeaturesInner
    ]?

    public init(
        id: Double? = nil,
        name: String? = nil,
        packageFeatures: [
            DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackagePackageFeaturesInner
        ]? =
            nil
    ) {
        self.id = id
        self.name = name
        self.packageFeatures = packageFeatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case packageFeatures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(packageFeatures, forKey: .packageFeatures)
    }
}
