//
// DescribeAccessToken200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseData: Codable, JSONEncodable, Hashable, QuestionChoice {
    public var identityId: Int
    public var identity: DescribeAccessToken200ResponseDataIdentity
    public var token: String
    public var tokenScopeList: [DescribeAccessToken200ResponseDataTokenScopeListInner]
    public var createdAt: Date?
    public var expiresAt: Date?

    public var id: Int { identityId }

    public var description: String {
        identity.namespace?.nickname ?? "<unnamed>"
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identityId
        case identity
        case token
        case tokenScopeList
        case createdAt
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identityId, forKey: .identityId)
        try container.encodeIfPresent(identity, forKey: .identity)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(tokenScopeList, forKey: .tokenScopeList)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}
