//
// DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackagePackageFeaturesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataTokenScopeListInnerOrgPackagePlansInnerPackagePackageFeaturesInner: Codable,
    JSONEncodable, Hashable {
    public var id: Double?
    public var config: AnyCodable?
    public var feature: GlobalListWirelessLockGateways200ResponseDataInnerAcuLocationRestrictionLocationMeasurementLocationMeasurementSourceType?

    public init(
        id: Double? = nil,
        config: AnyCodable? = nil,
        feature: GlobalListWirelessLockGateways200ResponseDataInnerAcuLocationRestrictionLocationMeasurementLocationMeasurementSourceType? =
            nil
    ) {
        self.id = id
        self.config = config
        self.feature = feature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case config
        case feature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(feature, forKey: .feature)
    }
}
