//
// DescribeAccessToken200ResponseDataTokenScopeListInnerScopeWithContextInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DescribeAccessToken200ResponseDataTokenScopeListInnerScopeWithContextInner: Codable, JSONEncodable,
    Hashable {
    public var context: [DescribeAccessToken200ResponseDataTokenScopeListInnerScopeWithContextInnerContextInner]?
    public var scope: [String]?

    public init(
        context: [DescribeAccessToken200ResponseDataTokenScopeListInnerScopeWithContextInnerContextInner]? = nil,
        scope: [String]? = nil
    ) {
        self.context = context
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(scope, forKey: .scope)
    }
}
