//
// GenerateSetupMobileTokenFromDeviceIdentifierRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateSetupMobileTokenFromDeviceIdentifierRequest: Codable, JSONEncodable, Hashable {
    public var deviceIdentifier: String

    public init(deviceIdentifier: String) {
        self.deviceIdentifier = deviceIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceIdentifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceIdentifier, forKey: .deviceIdentifier)
    }
}
