//
// GenerateSetupMobileTokenFromDeviceIdentifier201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateSetupMobileTokenFromDeviceIdentifier201ResponseData: Codable, JSONEncodable, Hashable {
    public var setupMobileToken: String

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setupMobileToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(setupMobileToken, forKey: .setupMobileToken)
    }
}
