//
// GlobalListBadgeDefaultConfigs200ResponseDataInnerCustomField1Config.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListBadgeDefaultConfigs200ResponseDataInnerCustomField1Config: Codable, JSONEncodable, Hashable {
    public enum TextAlign: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _left = "left"
        case center
        case _right = "right"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }

    public var isEnabled: Bool?
    public var color: String?
    public var fontFamily: String?
    public var fontSize: Double?
    public var lineHeight: Double?
    public var fontWeight: Double?
    public var textAlign: TextAlign?
    public var centerX: Double?
    public var centerY: Double?
    public var width: Double?
    public var height: Double?

    public init(
        isEnabled: Bool? = nil,
        color: String? = nil,
        fontFamily: String? = nil,
        fontSize: Double? = nil,
        lineHeight: Double? = nil,
        fontWeight: Double? = nil,
        textAlign: TextAlign? = nil,
        centerX: Double? = nil,
        centerY: Double? = nil,
        width: Double? = nil,
        height: Double? = nil
    ) {
        self.isEnabled = isEnabled
        self.color = color
        self.fontFamily = fontFamily
        self.fontSize = fontSize
        self.lineHeight = lineHeight
        self.fontWeight = fontWeight
        self.textAlign = textAlign
        self.centerX = centerX
        self.centerY = centerY
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isEnabled
        case color
        case fontFamily
        case fontSize
        case lineHeight
        case fontWeight
        case textAlign
        case centerX
        case centerY
        case width
        case height
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isEnabled, forKey: .isEnabled)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(fontFamily, forKey: .fontFamily)
        try container.encodeIfPresent(fontSize, forKey: .fontSize)
        try container.encodeIfPresent(lineHeight, forKey: .lineHeight)
        try container.encodeIfPresent(fontWeight, forKey: .fontWeight)
        try container.encodeIfPresent(textAlign, forKey: .textAlign)
        try container.encodeIfPresent(centerX, forKey: .centerX)
        try container.encodeIfPresent(centerY, forKey: .centerY)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
    }
}
