//
// GlobalListBadgeDefaultConfigs200ResponseDataInnerBackgroundPicture.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListBadgeDefaultConfigs200ResponseDataInnerBackgroundPicture: Codable, JSONEncodable, Hashable {
    public var contentType: String?
    public var fileName: String?
    public var url: String?

    public init(contentType: String? = nil, fileName: String? = nil, url: String? = nil) {
        self.contentType = contentType
        self.fileName = fileName
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType
        case fileName
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(fileName, forKey: .fileName)
        try container.encodeIfPresent(url, forKey: .url)
    }
}
