//
// GlobalListAcus200ResponseDataInnerLocationRestriction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListAcus200ResponseDataInnerLocationRestriction: Codable, JSONEncodable, Hashable {
    public var id: Int?
    public var locationMeasurement: GlobalListAcus200ResponseDataInnerLocationRestrictionLocationMeasurement?
    public var allowedDistanceMeters: Double?
    public var scaleFactor: Double?

    public init(
        id: Int? = nil,
        locationMeasurement: GlobalListAcus200ResponseDataInnerLocationRestrictionLocationMeasurement? = nil,
        allowedDistanceMeters: Double? = nil,
        scaleFactor: Double? = nil
    ) {
        self.id = id
        self.locationMeasurement = locationMeasurement
        self.allowedDistanceMeters = allowedDistanceMeters
        self.scaleFactor = scaleFactor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case locationMeasurement
        case allowedDistanceMeters
        case scaleFactor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(locationMeasurement, forKey: .locationMeasurement)
        try container.encodeIfPresent(allowedDistanceMeters, forKey: .allowedDistanceMeters)
        try container.encodeIfPresent(scaleFactor, forKey: .scaleFactor)
    }
}
