//
// GlobalListAcus200ResponseDataInnerAcuModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListAcus200ResponseDataInnerAcuModel: Codable, JSONEncodable, Hashable {
    public var id: Int?
    public var name: String?
    public var isBaseModel: Bool?

    public init(id: Int? = nil, name: String? = nil, isBaseModel: Bool? = nil) {
        self.id = id
        self.name = name
        self.isBaseModel = isBaseModel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isBaseModel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isBaseModel, forKey: .isBaseModel)
    }
}
