//
// GlobalListBadgeDefaultConfigs200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListBadgeDefaultConfigs200Response: Codable, JSONEncodable, Hashable {
    public var totalCount: Int?
    public var filteredCount: Int?
    public var data: [GlobalListBadgeDefaultConfigs200ResponseDataInner]?
    public var meta: ListAcuDeployTags200ResponseMeta?

    public init(
        totalCount: Int? = nil,
        filteredCount: Int? = nil,
        data: [GlobalListBadgeDefaultConfigs200ResponseDataInner]? = nil,
        meta: ListAcuDeployTags200ResponseMeta? = nil
    ) {
        self.totalCount = totalCount
        self.filteredCount = filteredCount
        self.data = data
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case filteredCount
        case data
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(filteredCount, forKey: .filteredCount)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}
