//
// GlobalListAcus200ResponseDataInnerLocationRestrictionLocationMeasurement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListAcus200ResponseDataInnerLocationRestrictionLocationMeasurement: Codable, JSONEncodable,
    Hashable {
    public var longitude: Double?
    public var latitude: Double?
    public var timeZoneId: String?

    public init(longitude: Double? = nil, latitude: Double? = nil, timeZoneId: String? = nil) {
        self.longitude = longitude
        self.latitude = latitude
        self.timeZoneId = timeZoneId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case longitude
        case latitude
        case timeZoneId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(timeZoneId, forKey: .timeZoneId)
    }
}
