//
// GlobalListAcus200ResponseDataInnerShadow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalListAcus200ResponseDataInnerShadow: Codable, JSONEncodable, Hashable {
    public var error: String?
    public var state: AnyCodable?
    public var metadata: AnyCodable?
    public var version: Int?
    public var timestamp: Int?

    public init(
        error: String? = nil,
        state: AnyCodable? = nil,
        metadata: AnyCodable? = nil,
        version: Int? = nil,
        timestamp: Int? = nil
    ) {
        self.error = error
        self.state = state
        self.metadata = metadata
        self.version = version
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case state
        case metadata
        case version
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}
