//
// ListCredentialConfigs200ResponseDataInnerCredentialEventAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialEventAction: Codable, JSONEncodable, Hashable {
    public enum Command: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case triggerlockdown = "triggerLockdown"
        case revertlockdown = "revertLockdown"
        case unlockwithoverride = "unlockWithOverride"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }

    public var credentialId: Double?
    public var command: Command
    public var targetId: Double?

    public init(credentialId: Double? = nil, command: Command, targetId: Double? = nil) {
        self.credentialId = credentialId
        self.command = command
        self.targetId = targetId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credentialId
        case command
        case targetId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(credentialId, forKey: .credentialId)
        try container.encode(command, forKey: .command)
        try container.encodeIfPresent(targetId, forKey: .targetId)
    }
}
