//
// ListCredentialConfigs200ResponseDataInnerCredentialCardCardFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialCardCardFormat: Codable, JSONEncodable, Hashable {
    public var id: Int
    public var code: String?
    public var numBits: Int?

    public init(id: Int, code: String? = nil, numBits: Int? = nil) {
        self.id = id
        self.code = code
        self.numBits = numBits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case numBits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(numBits, forKey: .numBits)
    }
}
