//
// ListAcuDeployTags200ResponseMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListAcuDeployTags200ResponseMeta: Codable, JSONEncodable, Hashable {
    public var accessToken: ListAcuDeployTags200ResponseMetaAccessToken?
    public var siteSpecificAccess: ListAcuDeployTags200ResponseMetaSiteSpecificAccess?

    public init(
        accessToken: ListAcuDeployTags200ResponseMetaAccessToken? = nil,
        siteSpecificAccess: ListAcuDeployTags200ResponseMetaSiteSpecificAccess? = nil
    ) {
        self.accessToken = accessToken
        self.siteSpecificAccess = siteSpecificAccess
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken
        case siteSpecificAccess
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(siteSpecificAccess, forKey: .siteSpecificAccess)
    }
}
