//
// ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInner: Codable, JSONEncodable,
    Hashable {
    public var id: Double?
    public var name: String?
    public var description: String?
    public var isDefault: Bool?
    public var buildingFloor: ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInnerBuildingFloor?

    public init(
        id: Double? = nil,
        name: String? = nil,
        description: String? = nil,
        isDefault: Bool? = nil,
        buildingFloor: ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInnerBuildingFloor? =
            nil
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.isDefault = isDefault
        self.buildingFloor = buildingFloor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case isDefault
        case buildingFloor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(buildingFloor, forKey: .buildingFloor)
    }
}
