//
// ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInnerCustomField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInnerCustomField: Codable,
    JSONEncodable, Hashable {
    public var id: Double?
    public var name: String?
    public var customFieldType: ListCredentialConfigs200ResponseDataInnerOrg?

    public init(
        id: Double? = nil,
        name: String? = nil,
        customFieldType: ListCredentialConfigs200ResponseDataInnerOrg? = nil
    ) {
        self.id = id
        self.name = name
        self.customFieldType = customFieldType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case customFieldType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(customFieldType, forKey: .customFieldType)
    }
}
