//
// ListCredentialConfigs200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200Response: Codable, JSONEncodable, Hashable {
    public var totalCount: Int?
    public var filteredCount: Int?
    public var data: [ListCredentialConfigs200ResponseDataInner]?
    public var meta: ListAcuDeployTags200ResponseMeta?

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalCount
        case filteredCount
        case data
        case meta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
        try container.encodeIfPresent(filteredCount, forKey: .filteredCount)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(meta, forKey: .meta)
    }
}
