//
// ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInner: Codable, JSONEncodable,
    Hashable {
    public var id: Double?
    public var value: String?
    public var customField: ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInnerCustomField?

    public init(
        id: Double? = nil,
        value: String? = nil,
        customField: ListCredentialConfigs200ResponseDataInnerCredentialUserUserCustomFieldsInnerCustomField? = nil
    ) {
        self.id = id
        self.value = value
        self.customField = customField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
        case customField
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(customField, forKey: .customField)
    }
}
