//
// ListCredentialConfigs200ResponseDataInnerCredentialUserIdentityMfaCredentialsInnerTotpSoftDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialUserIdentityMfaCredentialsInnerTotpSoftDevice: Codable,
    JSONEncodable, Hashable {
    public var id: Double?

    public init(id: Double? = nil) {
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
    }
}
