//
// ListCredentialConfigs200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInner: Codable, JSONEncodable, Hashable {
    public var id: Double?
    public var org: ListCredentialConfigs200ResponseDataInnerOrg?
    public var credential: ListCredentialConfigs200ResponseDataInnerCredential?
    public var config: ListCredentialConfigs200ResponseDataInnerConfig?

    public init(
        id: Double? = nil,
        org: ListCredentialConfigs200ResponseDataInnerOrg? = nil,
        credential: ListCredentialConfigs200ResponseDataInnerCredential? = nil,
        config: ListCredentialConfigs200ResponseDataInnerConfig? = nil
    ) {
        self.id = id
        self.org = org
        self.credential = credential
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case org
        case credential
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(org, forKey: .org)
        try container.encodeIfPresent(credential, forKey: .credential)
        try container.encodeIfPresent(config, forKey: .config)
    }
}
