//
// ListCredentialConfigs200ResponseDataInnerCredentialCloudKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialCloudKey: Codable, JSONEncodable, Hashable {
    public var id: Double?
    public var name: String?
    public var maxDurationSeconds: Double?

    public init(id: Double? = nil, name: String? = nil, maxDurationSeconds: Double? = nil) {
        self.id = id
        self.name = name
        self.maxDurationSeconds = maxDurationSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case maxDurationSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(maxDurationSeconds, forKey: .maxDurationSeconds)
    }
}
