//
// ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInnerBuildingFloor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialUserBuildingFloorUnitsInnerBuildingFloor: Codable,
    JSONEncodable, Hashable {
    public var id: Int?
    public var name: String?
    public var isDefault: Bool?
    public var building: GlobalListAcus200ResponseDataInnerOrg?

    public init(
        id: Int? = nil,
        name: String? = nil,
        isDefault: Bool? = nil,
        building: GlobalListAcus200ResponseDataInnerOrg? = nil
    ) {
        self.id = id
        self.name = name
        self.isDefault = isDefault
        self.building = building
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isDefault
        case building
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(building, forKey: .building)
    }
}
