//
// ListCredentialConfigs200ResponseDataInnerCredentialMobileUserIotCert.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialMobileUserIotCert: Codable, JSONEncodable, Hashable {
    public var id: Double?
    public var awsIotCertArn: String?
    public var certOpal: String?

    public init(id: Double? = nil, awsIotCertArn: String? = nil, certOpal: String? = nil) {
        self.id = id
        self.awsIotCertArn = awsIotCertArn
        self.certOpal = certOpal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case awsIotCertArn
        case certOpal
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(awsIotCertArn, forKey: .awsIotCertArn)
        try container.encodeIfPresent(certOpal, forKey: .certOpal)
    }
}
