//
// ListAcuDeployTags200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListAcuDeployTags200ResponseDataInner: Codable, JSONEncodable, Hashable {
    public var acuId: Int
    public var deployTagCode: String
    public var id: Int
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(acuId: Int, deployTagCode: String, id: Int, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.acuId = acuId
        self.deployTagCode = deployTagCode
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case acuId
        case deployTagCode
        case id
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(acuId, forKey: .acuId)
        try container.encode(deployTagCode, forKey: .deployTagCode)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}
