//
// ListCredentialConfigs200ResponseDataInnerCredentialCredentialType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCredentialConfigs200ResponseDataInnerCredentialCredentialType: Codable, JSONEncodable, Hashable {
    public var id: Int
    public var name: String?
    public var modelName: String?

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case modelName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(modelName, forKey: .modelName)
    }
}
