//
// LoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginRequest: Codable, JSONEncodable, Hashable {
    public var namespaceId: Int?
    public var namespaceNickname: String?
    public var email: String
    public var password: String
    public var mfa: LoginRequestMfa?
    public var forMobileLogin: Bool?

    public init(
        namespaceId: Int? = nil,
        namespaceNickname: String? = nil,
        email: String,
        password: String,
        mfa: LoginRequestMfa? = nil,
        forMobileLogin: Bool? = nil
    ) {
        self.namespaceId = namespaceId
        self.namespaceNickname = namespaceNickname
        self.email = email
        self.password = password
        self.mfa = mfa
        self.forMobileLogin = forMobileLogin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespaceId
        case namespaceNickname
        case email
        case password
        case mfa
        case forMobileLogin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(namespaceId, forKey: .namespaceId)
        try container.encodeIfPresent(namespaceNickname, forKey: .namespaceNickname)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(mfa, forKey: .mfa)
        try container.encodeIfPresent(forMobileLogin, forKey: .forMobileLogin)
    }
}
