//
// LoginRequestMfa.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginRequestMfa: Codable, JSONEncodable, Hashable {
    public var totpCode: String?

    public init(totpCode: String? = nil) {
        self.totpCode = totpCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totpCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totpCode, forKey: .totpCode)
    }
}
