//
// LoginAllRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginAllRequest: Codable, JSONEncodable, Hashable {
    public var email: String
    public var password: String
    public var mfa: LoginRequestMfa?
    public var forMobileLogin: Bool?

    public init(email: String, password: String, mfa: LoginRequestMfa? = nil, forMobileLogin: Bool? = nil) {
        self.email = email
        self.password = password
        self.mfa = mfa
        self.forMobileLogin = forMobileLogin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case mfa
        case forMobileLogin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(mfa, forKey: .mfa)
        try container.encodeIfPresent(forMobileLogin, forKey: .forMobileLogin)
    }
}
