{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If viewing this documentation in XCode, be sure to choose “Swift” as the language, both in the sidebar and above."}]}],"type":"aside","name":"Important"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"select-swift.png"}]},{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"anchor":"Adding-the-SDK-to-your-project","level":3,"type":"heading","text":"Adding the SDK to your project"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK is provided as a binary framework in a CocoaPods package, delivered in a "},{"type":"codeVoice","code":".zip"},{"type":"text","text":" file. The package also includes binary frameworks for all closed-source dependencies of the SDK."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To integrate the SDK:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set up CocoaPods for your app, if it is not already. Refer to CocoaPods documentation for details."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable dynamic frameworks in your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}]}]}]},{"type":"codeListing","syntax":"ruby","code":["  use_frameworks!"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unzip the SDK archive in a known location."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add the following to your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" in the section for your app target, filling in the correct SDK directory:"}]}]}]},{"type":"codeListing","syntax":"ruby","code":["  pod 'OpenpathMobile', path: '\/sdk\/directory'"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add a "},{"type":"codeVoice","code":"post_install"},{"type":"text","text":" hook to your Podfile as needed, as shown below and in the Example app."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure your app is using Swift 5.x"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enable the “Build Libraries for Distribution” setting as needed (see below)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"From the terminal, run "},{"type":"codeVoice","code":"pod install"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Build and run your app within Xcode"}]}]}]},{"anchor":"The-Build-Libraries-for-Distribution-setting","level":3,"type":"heading","text":"The “Build Libraries for Distribution” setting."},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the SDK is distributed in binary form, the SDK’s dependencies must be built with the “Build Libraries for Distribution” build flag set to "},{"type":"strong","inlineContent":[{"type":"text","text":"Yes"}]},{"type":"text","text":". This tells Xcode to build those dependencies in such a way that the SDK can call into them without needing to be recompiled."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For a simple app, this can be accomplished with the following steps:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, select the build settings for your app target, and chose "},{"type":"strong","inlineContent":[{"type":"text","text":"Yes"}]},{"type":"text","text":" for “Build Libraries for Distribution”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"From the terminal run (or re-run) "},{"type":"codeVoice","code":"pod install"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cocoapods will apply that build setting to all Pod projects, including "},{"type":"codeVoice","code":"OpenpathMobile"},{"type":"text","text":" and all its dependencies."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In a more complex app, you may not want to apply that setting to all Pod projects. For example, this can cause problems with some React Native libraries. In that case, here’s some code you can add to your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" that will apply the setting only to OpenpathMobile’s dependencies:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add this somewhere near the top of the Podfile:"}]}]}]},{"type":"codeListing","syntax":"ruby","code":["def get_dependencies_recursively(installer, root)","  top_dependencies = installer.pod_targets.find { |pt| pt.name == root }.dependencies","  dependencies = top_dependencies.to_set","  top_dependencies.each do |dep|","    dependencies.merge(get_dependencies_recursively(installer, dep)) if dep != root","  end","  dependencies.to_a","end","","def openpath_postinstall(installer)","  openpath_dependencies = get_dependencies_recursively(installer, 'OpenpathMobile')","  installer.generated_projects.each do |project|","    project.targets.each do |target|","      next unless openpath_dependencies.include?(target.name)","","      puts \"Target #{target} is an Openpath dependency, so setting BUILD_LIBRARY_FOR_DISTRIBUTION\"","      target.build_configurations.each do |config|","        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'","        # Some depended-on Pods set this to an obsolete iOS version","        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'","        # None of the Openpath dependencies need to be signed","        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'","      end","    end","  end","end"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Add a post_install block to the Podfile, or add to your existing one:"}]}]}]},{"type":"codeListing","syntax":"ruby","code":["  post_install do |installer|","    openpath_postinstall installer","","    # Any other post_install scripts go here","  end"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Re-run "},{"type":"codeVoice","code":"pod install"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reload the app in Xcode and rebuild"}]}]}]},{"anchor":"Enabling-background-modes-and-privacy-keys","level":3,"type":"heading","text":"Enabling background modes and privacy keys"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Openpath SDK requires the ability to access Bluetooth and location while the app is in the background. (The user will be prompted to approve these permissions interactively on first use.)"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure your app’s "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" file contains the following "},{"type":"strong","inlineContent":[{"type":"text","text":"background modes"}]},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"xml","code":["<key>UIBackgroundModes<\/key>","<array>","    <string>bluetooth-central<\/string>","    <string>location<\/string>","<\/array>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Openpath requires that the user has the following settings on their phone:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Global) Bluetooth -> ON"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Global) Location Services -> ON"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(optional) (Global) Fitness Tracking -> ON"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Openpath Bluetooth Permission -> Enabled"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Openpath Location Permission"}]}]}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ALWAYS - for Wave\/Touch to unlock reliably"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"WHEN IN USE - for unlocks only when the app is opened"}]}]}]},{"type":"orderedList","start":6,"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(optional) Openpath Motion & Fitness Permission -> Enabled"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Bluetooth"}]},{"type":"text","text":" and "},{"type":"strong","inlineContent":[{"type":"text","text":"Location Services"}]},{"type":"text","text":" are used to communicate with Openpath readers, to ensure that the app properly wakes up when near readers, and to allow the Wave feature to work reliably. Openpath never tracks or stores a user’s location information for any other purpose. "},{"type":"strong","inlineContent":[{"type":"text","text":"Motion & Fitness"}]},{"type":"text","text":" is used to help save battery and reduce data usage, as Openpath will turn off unnecessary activity if the phone is stationary."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Include the following "},{"type":"strong","inlineContent":[{"type":"text","text":"privacy keys"}]},{"type":"text","text":" in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" so that when a user is prompted for permission, the given text is displayed. The strings below are examples, and you may re-word them as you wish."}]},{"type":"codeListing","syntax":"xml","code":["<key>NSBluetoothAlwaysUsageDescription<\/key>","<string>We need access to Bluetooth to discover and unlock nearby entries.<\/string>","<key>NSBluetoothPeripheralUsageDescription<\/key>","<string>We need access to Bluetooth to discover and unlock nearby entries.<\/string>","<key>NSLocationAlwaysAndWhenInUseUsageDescription<\/key>","<string>"," We need \"Always\" location permission in order to discover nearby entries when the app is"," closed. This allows you to unlock via \"Touch\" without opening your phone. We do not store,"," log, or share your location data.","<\/string>","<key>NSLocationAlwaysUsageDescription<\/key>","<string>"," We need \"Always\" location permission in order to discover nearby entries when the app is"," closed. This allows you to unlock via \"Touch\" without opening your phone. We do not store,"," log, or share your location data.","<\/string>","<key>NSLocationWhenInUseUsageDescription<\/key>","<string>"," We need \"While Using App\" location permission in order to discover nearby entries. We do not"," store, log, or share your location data.","<\/string>","<key>NSMotionUsageDescription<\/key>","<string>"," We use motion to turn off services when your phone is stationary in order to save battery"," and reduce data usage.","<\/string>"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For iOS14, Apple added the ability for location accuracy to be reduced or approximated. In order for unlocks to be verified as “on-site” and near a reader according to geofence rules, the SDK needs full location accuracy, so this setting must be off. The following can be added to your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" file, though the default value is "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if this key is not included."}]},{"type":"codeListing","syntax":"xml","code":["<key>NSLocationDefaultAccuracyReduced<\/key>","<false\/>"]},{"anchor":"Beacon-Region-Monitoring","level":3,"type":"heading","text":"Beacon Region Monitoring"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Openpath SDK uses "},{"type":"strong","inlineContent":[{"type":"text","text":"beacon region monitoring"}]},{"type":"text","text":" so the SDK can wake up and start services when the device comes within range of readers."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Apple allows for a maximum of 20 beacons regions to be monitored per app. Openpath monitors 11 regions, so there are 9 remaining regions available for your use."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to help prevent region identifier collision, Openpath regions are prefixed with "},{"type":"codeVoice","code":"op-beacon"},{"type":"text","text":"."}]},{"anchor":"Using-the-OpenpathMobileAccessCore-class","level":3,"type":"heading","text":"Using the OpenpathMobileAccessCore class"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you’ve added the framework to your project, updated "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":", and installed the CocoaPods libraries, you are ready to write some code."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"},{"type":"text","text":" class is a singleton, available through the "},{"type":"codeVoice","code":"shared"},{"type":"text","text":" static variable."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set your class as the SDK’s delegate:"}]},{"type":"codeListing","syntax":"swift","code":["class MyClass: OpenpathMobileAccessCoreDelegate {","  init() {","    OpenpathMobileAccessCore.shared.delegate = self","  }","}"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"IMPORTANT: Always access "},{"type":"codeVoice","code":"OpenpathMobileAccessCore.shared"},{"type":"text","text":" on the main thread."}]}]},{"anchor":"iOS-Example-App","level":3,"type":"heading","text":"iOS Example App"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The iOS example app uses the Openpath Mobile Access Core SDK to:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Provision one or more user mobile credentials onto the app"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Switch between users on the app"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"View the list of entries that the user has access to"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unlock an entry"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Unprovision all the users or select one to unprovision from the list of inactive users"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Example App targets iOS 15+ and uses advanced features that may not be available in previous iOS versions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For the purposes of this demo, we will show provisioning through two different ways."}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The app can be provisioned via email and password by allowing a user to log in and generate their own mobile setup token to use for provisioning. Usually, only a user with admin rights to the Openpath Control Center (admin portal) has a password."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The app can be provisioned via mobile setup token. In practice, most users won’t have an Openpath password. We recommend that you create a service user (super admin) in the Openpath Control Center, and use that service user in your cloud to make Openpath API calls to generate a temporary mobile setup token for a particular user’s mobile credential. Then this token should be passed from your cloud server to the mobile app and into the “provision” SDK function."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information on the provisioning workflow, please refer to the Openpath Mobile Access SDK README section entitled “Provisioning Workflow”."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openpathmobile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openpathmobile"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"OpenpathMobile","title":"OpenpathMobile","symbolKind":"module","role":"collection","modules":[{"name":"OpenpathMobile"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.3.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.2","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.3","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.4"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/UdpClient"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathAnalyticsDelegate","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/NullCodable","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathError","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathTermsOfUseStatus","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathUser","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ProvisionResult"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionNumber","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/AuthorizationStatusType","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ResultMessage"]},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/CoreLocation","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Swift"]}],"references":{"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathUser":{"role":"symbol","title":"OpenpathUser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathUser"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathUser"}],"url":"\/documentation\/openpathmobile\/openpathuser"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCore":{"role":"symbol","title":"OpenpathMobileAccessCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"abstract":[{"type":"text","text":"The entry point for all functionality in the OpenpathMobile SDK."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscore"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.4.4":{"role":"article","title":"iOS SDK Release v0.4.4","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.4","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.4.4"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.2.1":{"role":"article","title":"Release v0.2.1","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.1","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.2.1"},"select-swift.png":{"alt":"Select Swift in two places","type":"image","identifier":"select-swift.png","variants":[{"url":"\/images\/select-swift.png","traits":["1x","light"]}]},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/NullCodable":{"role":"symbol","title":"NullCodable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NullCodable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/NullCodable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NullCodable"}],"url":"\/documentation\/openpathmobile\/nullcodable"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/ProvisionResult":{"role":"symbol","title":"ProvisionResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProvisionResult"}],"abstract":[{"type":"text","text":"Represents the result of a call to "},{"type":"codeVoice","code":"provision"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ProvisionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProvisionResult"}],"url":"\/documentation\/openpathmobile\/provisionresult"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.1.1":{"role":"article","title":"Release v0.1.1","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.1","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.1.1"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathTermsOfUseStatus":{"role":"symbol","title":"OpenpathTermsOfUseStatus","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathTermsOfUseStatus"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathTermsOfUseStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathTermsOfUseStatus"}],"url":"\/documentation\/openpathmobile\/openpathtermsofusestatus"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/AuthorizationStatusType":{"role":"symbol","title":"AuthorizationStatusType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthorizationStatusType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/AuthorizationStatusType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthorizationStatusType"}],"url":"\/documentation\/openpathmobile\/authorizationstatustype"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Swift":{"role":"collection","title":"Swift","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Swift","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/swift"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/ObjcExceptionBridgingVersionString":{"role":"symbol","title":"ObjcExceptionBridgingVersionString","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcExceptionBridgingVersionString"},{"kind":"text","text":": <<error type>>"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionString","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/objcexceptionbridgingversionstring"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileAccessCoreDelegate":{"role":"symbol","title":"OpenpathMobileAccessCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"abstract":[{"type":"text","text":"Delegate class for receiving asynchronous results and events from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCoreDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathMobileAccessCoreDelegate"}],"url":"\/documentation\/openpathmobile\/openpathmobileaccesscoredelegate"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.4.3":{"role":"article","title":"iOS SDK Release v0.4.3","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.3","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.4.3"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.2.0":{"role":"article","title":"Release v0.2.0","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.0","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.2.0"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.1.0":{"role":"article","title":"Release v0.1.0","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.0","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.1.0"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathError":{"role":"symbol","title":"OpenpathError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathError"}],"url":"\/documentation\/openpathmobile\/openpatherror"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileVersionNumber":{"role":"symbol","title":"OpenpathMobileVersionNumber","fragments":[{"kind":"identifier","text":"OpenpathMobileVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileversionnumber"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathMobileVersionString":{"role":"symbol","title":"OpenpathMobileVersionString","fragments":[{"kind":"identifier","text":"OpenpathMobileVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileVersionString","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/openpathmobileversionstring"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/OpenpathAnalyticsDelegate":{"role":"symbol","title":"OpenpathAnalyticsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OpenpathAnalyticsDelegate"}],"abstract":[{"type":"text","text":"Delegate class for receiving asynchronous analytics events from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathAnalyticsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OpenpathAnalyticsDelegate"}],"url":"\/documentation\/openpathmobile\/openpathanalyticsdelegate"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.4.2":{"role":"article","title":"iOS SDK Release v0.4.2","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.2","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.4.2"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.3.0":{"role":"article","title":"Release v0.3.0","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.3.0","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.3.0"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/ObjcExceptionBridgingVersionNumber":{"role":"symbol","title":"ObjcExceptionBridgingVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjcExceptionBridgingVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ObjcExceptionBridgingVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/objcexceptionbridgingversionnumber"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile":{"role":"collection","title":"OpenpathMobile","abstract":[{"type":"text","text":"The SDK that provides access to Openpath functionality for iOS-based mobile devices."}],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.4.1":{"role":"article","title":"Release v0.4.1","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.1","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.4.1"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/UdpClient":{"role":"symbol","title":"UdpClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UdpClient"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/UdpClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UdpClient"}],"url":"\/documentation\/openpathmobile\/udpclient"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/ResultMessage":{"role":"symbol","title":"ResultMessage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/ResultMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultMessage"}],"url":"\/documentation\/openpathmobile\/resultmessage"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/Release-0.4.0":{"role":"article","title":"Release v0.4.0","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.0","kind":"article","type":"topic","url":"\/documentation\/openpathmobile\/release-0.4.0"},"doc://org.cocoapods.OpenpathMobile/documentation/OpenpathMobile/CoreLocation":{"role":"collection","title":"CoreLocation","abstract":[],"identifier":"doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/CoreLocation","kind":"symbol","type":"topic","url":"\/documentation\/openpathmobile\/corelocation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.1.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.2.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.3.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.0","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.1","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.2","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.3","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/Release-0.4.4"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileAccessCore"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileVersionNumber","doc:\/\/org.cocoapods.OpenpathMobile\/documentation\/OpenpathMobile\/OpenpathMobileVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/title","value":"OpenpathMobileAccessCore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.OpenpathMobile~1documentation~1OpenpathMobile~1OpenpathMobileAccessCore\/fragments","value":[{"kind":"identifier","text":"OpenpathMobileAccessCore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}